name: Sync to Sheets
on:
  push:
    paths:
      - 'Invoices_Database.csv'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sheet Update
        run: curl -L -X POST "https://script.google.com/macros/s/AKfycbzYiLkIou2e3DYI15mZOVFYS_o8fB91qltkb4GDJQ4iXNdv6zxX4qgO-w6WdAG242N-/exec"
